[package]
name = "gpredict"
version = "0.2.3"
authors = ["Andres Vahter <andres.vahter@gmail.com>"]

[dependencies]
libc = "*"
time = "*"
log = "*"
rustc-serialize = "*"

[dev-dependencies]
log = "*"
fern = "*"
