[package]
name = "gpredict"
version = "0.2.4"
authors = ["Andres Vahter <andres.vahter@gmail.com>"]

[dependencies]
libc = "*"
time = "*"
log = "*"
rustc-serialize = "*"

[dev-dependencies]
log = "*"
fern = "*"

[dependencies.coordinates]
git = "https://github.com/cubehub/rust-coordinates.git"
